/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedCommandRouteImport } from './routes/_authenticated/command'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedProcurementRouteImport } from './routes/_authenticated/procurement'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedScenariosRouteImport } from './routes/_authenticated/scenarios'
import { Route as AuthenticatedSprRouteImport } from './routes/_authenticated/spr'
import { Route as AuthenticatedTwinRouteImport } from './routes/_authenticated/twin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandRoute = AuthenticatedCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementRoute =
  AuthenticatedProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScenariosRoute = AuthenticatedScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSprRoute = AuthenticatedSprRouteImport.update({
  id: '/spr',
  path: '/spr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTwinRoute = AuthenticatedTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/command': typeof AuthenticatedCommandRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scenarios': typeof AuthenticatedScenariosRoute
  '/spr': typeof AuthenticatedSprRoute
  '/twin': typeof AuthenticatedTwinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/command': typeof AuthenticatedCommandRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scenarios': typeof AuthenticatedScenariosRoute
  '/spr': typeof AuthenticatedSprRoute
  '/twin': typeof AuthenticatedTwinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/command': typeof AuthenticatedCommandRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/procurement': typeof AuthenticatedProcurementRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/scenarios': typeof AuthenticatedScenariosRoute
  '/_authenticated/spr': typeof AuthenticatedSprRoute
  '/_authenticated/twin': typeof AuthenticatedTwinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/command'
    | '/intelligence'
    | '/procurement'
    | '/reports'
    | '/scenarios'
    | '/spr'
    | '/twin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audit'
    | '/command'
    | '/intelligence'
    | '/procurement'
    | '/reports'
    | '/scenarios'
    | '/spr'
    | '/twin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit'
    | '/_authenticated/command'
    | '/_authenticated/intelligence'
    | '/_authenticated/procurement'
    | '/_authenticated/reports'
    | '/_authenticated/scenarios'
    | '/_authenticated/spr'
    | '/_authenticated/twin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command': {
      id: '/_authenticated/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AuthenticatedCommandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement': {
      id: '/_authenticated/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthenticatedProcurementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenarios': {
      id: '/_authenticated/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof AuthenticatedScenariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spr': {
      id: '/_authenticated/spr'
      path: '/spr'
      fullPath: '/spr'
      preLoaderRoute: typeof AuthenticatedSprRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/twin': {
      id: '/_authenticated/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof AuthenticatedTwinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCommandRoute: typeof AuthenticatedCommandRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedProcurementRoute: typeof AuthenticatedProcurementRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScenariosRoute: typeof AuthenticatedScenariosRoute
  AuthenticatedSprRoute: typeof AuthenticatedSprRoute
  AuthenticatedTwinRoute: typeof AuthenticatedTwinRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCommandRoute: AuthenticatedCommandRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedProcurementRoute: AuthenticatedProcurementRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScenariosRoute: AuthenticatedScenariosRoute,
  AuthenticatedSprRoute: AuthenticatedSprRoute,
  AuthenticatedTwinRoute: AuthenticatedTwinRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
